FROM nginx

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y build-essential python3 python3-pip python3-dev nano vim curl

WORKDIR /code
COPY . .

RUN pip install -r requirements.txt
RUN python3 manage.py collectstatic
COPY deployment/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /

#CMD bash /docker-entrypoint.sh
#CMD nginx
