# Generated by Django 4.2.6 on 2023-11-02 21:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("glug", "0001_initial"),
        ("hacktivist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetups",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField()),
                ("slug", models.SlugField(default="")),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offine", "Offline")]
                    ),
                ),
                ("venue", models.TextField()),
                ("description", models.TextField()),
                (
                    "poster",
                    models.ImageField(
                        null=True, upload_to="meetups/poster/", verbose_name="Poster"
                    ),
                ),
                (
                    "minutes",
                    models.FileField(
                        null=True,
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "glug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="glug.glug"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hacktivist.locations",
                    ),
                ),
            ],
        ),
    ]
