# Generated by Django 4.2.6 on 2023-11-02 19:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("glug", "0001_initial"),
        ("hacktivist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offine", "Offline")]
                    ),
                ),
                ("venue", models.TextField()),
                ("description", models.TextField()),
                (
                    "poster",
                    models.ImageField(
                        null=True, upload_to="meetups/poster/", verbose_name="Poster"
                    ),
                ),
                (
                    "minutes",
                    models.FileField(
                        null=True,
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "glug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="glug.glug"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hacktivist.locations",
                    ),
                ),
            ],
        ),
    ]
