# Generated by Django 4.2.6 on 2023-10-09 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meetups",
            old_name="platform",
            new_name="mode",
        ),
    ]
