# Generated by Django 4.2.6 on 2023-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetups",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
