# Generated by Django 4.2.6 on 2023-10-12 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0002_rename_platform_meetups_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetups",
            name="minutes",
        ),
    ]
