# Generated by Django 4.2.6 on 2023-10-12 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0002_rename_platform_meetups_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetups",
            name="minutes",
            field=models.FileField(
                upload_to="",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
