# Generated by Django 4.2.6 on 2023-10-16 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0003_alter_meetups_minutes"),
        ("meetups", "0003_remove_meetups_minutes"),
    ]

    operations = []
