# Generated by Django 4.2.6 on 2023-11-26 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetups", "0003_alter_meetups_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetups",
            name="interested_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_meetups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
