# Generated by Django 4.2.6 on 2023-12-01 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetups", "0004_meetups_interested_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetups",
            name="willattend_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="willattend_meetups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
