# Generated by Django 4.2.6 on 2023-10-18 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0004_merge_20231016_0633"),
    ]

    operations = []
