# Generated by Django 4.2.6 on 2023-10-18 11:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0005_remove_meetups_minutes"),
    ]

    operations = []
