# Generated by Django 4.2.6 on 2023-10-18 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0006_meetups_minutes"),
    ]

    operations = []
