# Generated by Django 4.2.6 on 2023-10-18 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0008_meetups_minutes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetups",
            name="minutes",
        ),
    ]
