# Generated by Django 4.2.6 on 2023-10-18 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0011_meetups_owner"),
    ]

    operations = []
