# Generated by Django 4.2.6 on 2023-10-20 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0012_alter_meetups_options_remove_meetups_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetups",
            options={},
        ),
    ]
