# Generated by Django 4.2.6 on 2023-10-27 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0014_meetups_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetups",
            name="minutes",
            field=models.FileField(
                null=True,
                upload_to="",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="meetups",
            name="poster",
            field=models.ImageField(
                null=True, upload_to="meetups/poster/", verbose_name="Poster"
            ),
        ),
    ]
