# Generated by Django 4.2.6 on 2023-10-30 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0015_alter_meetups_minutes_alter_meetups_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetups",
            name="title",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
