# Generated by Django 4.2.2 on 2023-06-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='members',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+ve', 'Op'), ('O-ve', 'On'), ('A+ve', 'Ap'), ('A-ve', 'An'), ('B+ve', 'Bp'), ('B-ve', 'Bn'), ('AB+ve', 'Abp'), ('AB-ve', 'Abn')], max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='display_pic',
            field=models.ImageField(default='defaults/user.png', upload_to='users/display_pics/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='dob',
            field=models.DateField(blank=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='members',
            name='edu_qualification',
            field=models.CharField(blank=True, choices=[('8th Pass', 'Eighth Pass'), ('10th Pass', 'Tenth Pass'), ('12th Pass', 'Twelveth Pass'), ('Diploma', 'Diploma'), ('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate'), ('Doctorate', 'Doctorate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Trans', 'Trans'), ('Queer', 'Queer'), ('Other', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='members',
            name='institute',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='institutions.institutions', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='members',
            name='occupation',
            field=models.CharField(blank=True, choices=[('School Student', 'S Student'), ('College/University Student', 'C Student'), ('Researcher', 'Researcher'), ('IT Employee', 'It Employee'), ('ITES Employee', 'Ites Employee'), ('Non IT/ITES Employee', 'Non It Ites Employee'), ('Self Employed', 'Self Employed'), ('Unemployed', 'Unemployed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='stream',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
