# Generated by Django 4.2.6 on 2023-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proofofpayment",
            name="transaction_id",
            field=models.CharField(max_length=30),
        ),
    ]
