# Generated by Django 4.2.2 on 2023-06-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_members_address_alter_members_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='display_pic',
            field=models.ImageField(default='defaults/user.png', upload_to='users/display_pics/', verbose_name='Profile picture'),
        ),
    ]
