# Generated by Django 4.2.6 on 2023-10-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0002_alter_membership_proof_of_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="join_date",
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="payment_pending",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.BooleanField(
                blank=True,
                choices=[(0, "Expried/Invalid"), (1, "Valid")],
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
