# Generated by Django 4.2.6 on 2023-10-07 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0003_alter_membership_join_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["-start_date", "member"],
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
        migrations.RemoveField(
            model_name="membership",
            name="year",
        ),
    ]
