# Generated by Django 4.2.2 on 2023-06-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glug', '0002_initial'),
        ('member', '0003_alter_members_display_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='contact',
            field=models.IntegerField(verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='members',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='members',
            name='glug',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='glug.glug', verbose_name='GLUG'),
        ),
    ]
