# Generated by Django 4.2.2 on 2023-06-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_members_contact_alter_members_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='contact',
            field=models.BigIntegerField(verbose_name='Contact'),
        ),
    ]
