# Generated by Django 4.2.2 on 2023-06-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glug', '0002_initial'),
        ('member', '0005_alter_members_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='glug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='glug.glug', verbose_name='GLUG'),
        ),
    ]
