# Generated by Django 4.2.2 on 2023-08-06 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_members_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_accept_TC',
            field=models.BooleanField(default=False, verbose_name='Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='members',
            name='is_news_subscribed',
            field=models.BooleanField(default=False, verbose_name='FOSS News updates'),
        ),
        migrations.AlterField(
            model_name='members',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+ve', 'O+ve'), ('O-ve', 'O-ve'), ('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve')], max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='edu_qualification',
            field=models.CharField(blank=True, choices=[('8th Pass', '8th Pass'), ('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('Diploma', 'Diploma'), ('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate'), ('Doctorate', 'Doctorate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='occupation',
            field=models.CharField(blank=True, choices=[('School Student', 'School Student'), ('College/University Student', 'College/University Student'), ('Researcher', 'Researcher'), ('IT Employee', 'IT Employee'), ('ITES Employee', 'ITES Employee'), ('Non IT/ITES Employee', 'Non IT/ITES Employee'), ('Self Employed', 'Self Employed'), ('Unemployed', 'Unemployed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='document',
            field=models.FileField(upload_to='users/payments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
