# Generated by Django 4.2.4 on 2023-08-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_members_unique_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='zip_code',
            new_name='country_code',
        ),
        migrations.AlterField(
            model_name='members',
            name='contact',
            field=models.CharField(max_length=10, verbose_name='Contact'),
        ),
    ]
