# Generated by Django 4.2.4 on 2023-08-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_rename_zip_code_members_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='contact_full',
        ),
    ]
