# Generated by Django 4.2.4 on 2023-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_remove_members_contact_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='profile_status',
            field=models.IntegerField(choices=[(1, 'Profile Info'), (2, 'Membership'), (3, 'Payment Proof'), (4, 'Proof Confirmation'), (5, 'Success')], default=1, verbose_name='Profile Status'),
        ),
    ]
