# Generated by Django 4.2.4 on 2023-08-30 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hacktivist', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLUG',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=256, verbose_name='GLUG Name')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institutions.institutions', verbose_name='Institute')),
                ('location', models.ForeignKey(help_text='Pick your GLUG location', on_delete=django.db.models.deletion.RESTRICT, to='hacktivist.locations', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'GNU/Linux Users Group',
                'verbose_name_plural': 'GNU/Linux Users Group',
                'ordering': ['name', '-updated_at'],
            },
        ),
    ]
