# Generated by Django 4.2.2 on 2023-06-12 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLUG',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=256, verbose_name='GLUG Name')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GNU/Linux Users Group',
                'verbose_name_plural': 'GNU/Linux Users Group',
                'ordering': ['name', '-updated_at'],
            },
        ),
    ]
