# Generated by Django 4.2.2 on 2023-06-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hacktivist', '0002_locations_location'),
        ('institutions', '0001_initial'),
        ('glug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glug',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institutions.institutions', verbose_name='Institute'),
        ),
        migrations.AddField(
            model_name='glug',
            name='location',
            field=models.ForeignKey(help_text='Pick your GLUG location', on_delete=django.db.models.deletion.RESTRICT, to='hacktivist.locations', verbose_name='Location'),
        ),
    ]
