# Generated by Django 4.2.4 on 2023-09-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institutions_address_and_more'),
        ('hacktivist', '0003_alter_locations_country_alter_locations_district_and_more'),
        ('glug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glug',
            name='institute',
            field=models.ForeignKey(help_text='Pick your Institute you are associated with.', on_delete=django.db.models.deletion.RESTRICT, to='institutions.institutions', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='glug',
            name='location',
            field=models.ForeignKey(help_text='Pick your GLUG location.', on_delete=django.db.models.deletion.RESTRICT, to='hacktivist.locations', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='glug',
            name='name',
            field=models.CharField(help_text='Enter your GLUG name.', max_length=256, verbose_name='GLUG Name'),
        ),
    ]
