# Generated by Django 4.2.6 on 2023-11-02 19:18

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, null=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("district", models.CharField(max_length=256, verbose_name="district")),
                ("state", models.CharField(max_length=256, verbose_name="state")),
                (
                    "country",
                    models.CharField(
                        default="India", max_length=256, verbose_name="country"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="point your Institution/GLUG location",
                        null=True,
                        srid=4326,
                        verbose_name="location",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subscription name",
                        max_length=256,
                        verbose_name="name",
                    ),
                ),
                (
                    "validity",
                    models.IntegerField(
                        default=1,
                        help_text="Validity of subscription in years",
                        verbose_name="Validity",
                    ),
                ),
                (
                    "occupation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("School Student", "School Student"),
                                (
                                    "College/University Student",
                                    "College/University Student",
                                ),
                                ("Researcher", "Researcher"),
                                ("IT Employee", "IT Employee"),
                                ("ITES Employee", "ITES Employee"),
                                ("Non IT/ITES Employee", "Non IT/ITES Employee"),
                                ("Self Employed", "Self Employed"),
                                ("Unemployed", "Unemployed"),
                            ],
                            max_length=256,
                        ),
                        blank=True,
                        null=True,
                        size=10,
                        verbose_name="Occupation",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="Price for the subscriptions", verbose_name="Price"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
    ]
