# Generated by Django 4.2.4 on 2023-09-01 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktivist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='country',
            field=models.CharField(default='India', help_text='', max_length=256, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='district',
            field=models.CharField(help_text='', max_length=256, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='state',
            field=models.CharField(help_text='', max_length=256, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='occupation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('School Student', 'School Student'), ('College/University Student', 'College/University Student'), ('Researcher', 'Researcher'), ('IT Employee', 'IT Employee'), ('ITES Employee', 'ITES Employee'), ('Non IT/ITES Employee', 'Non IT/ITES Employee'), ('Self Employed', 'Self Employed'), ('Unemployed', 'Unemployed')], max_length=256), blank=True, null=True, size=10, verbose_name='Occupation'),
        ),
    ]
