# Generated by Django 4.2.2 on 2023-06-10 14:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacktivist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='point your GLUG location', null=True, srid=4326, verbose_name='location'),
        ),
    ]
