# Generated by Django 4.2.4 on 2023-08-28 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacktivist', '0006_alter_locations_country_alter_locations_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='occupation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=10, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='validity',
            field=models.IntegerField(default=1, help_text='Validity of subscription in years', verbose_name='Validity'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='country',
            field=models.CharField(default='India', help_text='', max_length=256, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='district',
            field=models.CharField(help_text='', max_length=256, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='state',
            field=models.CharField(help_text='', max_length=256, verbose_name='state'),
        ),
    ]
