# Generated by Django 4.2.4 on 2023-09-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacktivist', '0003_alter_locations_country_alter_locations_district_and_more'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='address',
            field=models.TextField(help_text='Address of The Institute.', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='location',
            field=models.ForeignKey(help_text='Pick your Institute location.', on_delete=django.db.models.deletion.RESTRICT, to='hacktivist.locations', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='name',
            field=models.CharField(help_text='Enter your Institution name.', max_length=256, verbose_name='Institute Name'),
        ),
    ]
