# Generated by Django 5.0.2 on 2024-02-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("software", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
