# Generated by Django 4.2.6 on 2023-10-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("software", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="alternatives",
            field=models.ManyToManyField(
                blank=True, to="software.software", verbose_name="Alternative Softwares"
            ),
        ),
    ]
