# Generated by Django 4.2.6 on 2023-11-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("software", "0002_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="is_foss",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                null=True,
                verbose_name="is FOSS",
            ),
        ),
    ]
