# Generated by Django 4.2.6 on 2023-11-03 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("software", "0002_alter_software_alternatives"),
    ]

    operations = [
        migrations.AddField(
            model_name="software",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="page_home",
            field=models.URLField(
                blank=True, null=True, unique=True, verbose_name="Homepage"
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="url_wikipedia",
            field=models.URLField(
                blank=True, null=True, unique=True, verbose_name="Wikipedia URL"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
